language: python
install:
  - pip install -q coverage
  - pip install python-coveralls
python:
  - "2.7"
  - "3.4"
script: nosetests --with-coverage --cover-package=functional
after_success:
  - coveralls
